OrderSystem/OrderSystem/Controllers/OrderController.cs
using Common;
using Common.Enums;
using Domain.Model.Comapnys;
using Domain.Model.Orders;
using Domain.Model.Users;
using Domain.Services;
using Domain.Services.Companys;
using Domain.Services.Orders;
using Domain.Services.Products;
using Domain.Services.Stores;
using Domain.Services.Users;
using OrderSystem.Extensions;
using OrderSystem.Models.Orders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OrderSystem.Controllers
{
    public class OrderController : Controller
    {
        private IWorkContext _workContext;
        private IOrderService _orderService;
        private ISubordinateCompanyService _subordinateCompany;
        private IUserService _userService;
        private IStoreService _store;
        private ICatalogService _catalogService;
        private IProductService _productService;
        public OrderController(
            IProductService productService,
            ICatalogService catalogService,
            IStoreService store,
            IUserService userService,
            ISubordinateCompanyService subordinateCompany,
            IOrderService orderService,
            IWorkContext workContext)
        {
            _productService = productService;
            _catalogService = catalogService;
            _store = store;
            _userService = userService;
            _subordinateCompany = subordinateCompany;
            _orderService = orderService;
            _workContext = workContext;
        }

        #region 公用方法
        private Order ToOrder(OrderModel model)
        {
            return new Order
            {
                Address = model.Address,
                AgentId = model.AgentId,
                AreaCheckTime = model.AreaCheckTime,
                AreaId = model.AreaId,
                CancelTime = model.CancelTime,
                City = model.City,
                County = model.County,
                CreateTime = DateTime.Now,
                CreateUserId = _workContext.CurrentUser.Id,
                CustomerName = model.CustomerName,
                CustomerTel1 = model.CustomerTel1,
                CustomerTel2 = model.CustomerTel2,
                DGId = model.DGId,
                DGSubmitTime = model.DGSubmitTime,
                FWSID = model.FWSID,
                FWSSubmitStatus = model.FWSSubmitStatus,
                FWSSubmitTime = model.FWSSubmitTime,
                FWSUserCompleteTime = model.FWSUserCompleteTime,
                FWSUserName = model.FWSUserName,
                FWSUserSubmitStatus = model.FWSUserSubmitStatus,
                FWSUserSubmitTime = model.FWSUserSubmitTime,
                FWSUserTel = model.FWSUserTel,
                Id = model.Id,
                JSXCheckTime = model.JSXCheckTime,
                JXSId = model.JXSId,
                MDId = model.MDId,
                OrderNum = model.OrderNum,
                Province = model.Province,
                Remarks = model.Remarks,
                RequireDeliveryTime = model.RequireDeliveryTime,
                RequireInstallTime = model.RequireInstallTime,
                Status = model.Status,
                StoreId = model.StoreId,
                WLCheckTime = model.WLCheckTime,
                WLDeliverTime = model.WLDeliverTime
            };
        }

        public OrderModel ToModel(Order model)
        {
            return new OrderModel
            {
                Address = model.Address,
                AgentId = model.AgentId,
                AreaCheckTime = model.AreaCheckTime,
                AreaId = model.AreaId,
                CancelTime = model.CancelTime,
                City = model.City,
                County = model.County,
                CreateTime = DateTime.Now,
                CreateUserId = _workContext.CurrentUser.Id,
                CustomerName = model.CustomerName,
                CustomerTel1 = model.CustomerTel1,
                CustomerTel2 = model.CustomerTel2,
                DGId = model.DGId,
                DGSubmitTime = model.DGSubmitTime,
                FWSID = model.FWSID,
                FWSSubmitStatus = model.FWSSubmitStatus,
                FWSSubmitTime = model.FWSSubmitTime,
                FWSUserCompleteTime = model.FWSUserCompleteTime,
                FWSUserName = model.FWSUserName,
                FWSUserSubmitStatus = model.FWSUserSubmitStatus,
                FWSUserSubmitTime = model.FWSUserSubmitTime,
                FWSUserTel = model.FWSUserTel,
                Id = model.Id,
                JSXCheckTime = model.JSXCheckTime,
                JXSId = model.JXSId,
                MDId = model.MDId,
                OrderNum = model.OrderNum,
                Province = model.Province,
                Remarks = model.Remarks,
                RequireDeliveryTime = model.RequireDeliveryTime,
                RequireInstallTime = model.RequireInstallTime,
                Status = model.Status,
                StoreId = model.StoreId,
                WLCheckTime = model.WLCheckTime,
                WLDeliverTime = model.WLDeliverTime,
                DGName = model.DG == null ? "" : model.DG.Name,
                FWSName = model.FWS == null ? "" : model.FWS.Name,
                JXSName = model.JXS == null ? "" : model.JXS.Name,
                MDName = model.MD == null ? "" : model.MD.Name,
                StoreName = model.Store == null ? "" : model.Store.Name
            };
        }
        #endregion

        #region 订单管理
        // GET: Order
        public ActionResult OrderList()
        {
            return View();
        }

        public string GetOrderList()
        {
            //string title = Request.QueryString["title"] == null ? "" : Request.QueryString["title"].ToString();
            //int booktype = Request.QueryString["booktype"] == null ? -1 : Convert.ToInt32(Request.QueryString["booktype"]);
            //int knowledgeClass = Request.QueryString["knowledgeClass"] == null ? -1 : Convert.ToInt32(Request.QueryString["knowledgeClass"]);
            //DateTime? begintime = Request.QueryString["begintime"] == null ? new Nullable<DateTime>() : Convert.ToDateTime(Request.QueryString["begintime"]);
            //DateTime? endtime = Request.QueryString["endtime"] == null ? new Nullable<DateTime>() : Convert.ToDateTime(Request.QueryString["endtime"]);
            int pageSize = Convert.ToInt32(Request.QueryString["rows"]);
            int pageIndex = Convert.ToInt32(Request.QueryString["page"]) - 1;
            var data = _orderService.GetOrderList(_workContext.CurrentUser, pageIndex, pageSize);
            List<object> model = data.Select(p => (object)new
            {
                Id = p.Id,
                OrderNum = p.OrderNum,
                StatusId= p.Status,
                FWSUserSubmitStatus=p.FWSUserSubmitStatus,
                Status = EnumExtensions.GetEnumDescription((OrderStatus)p.Status),
                OrderTotal = p.OrderItems.Sum(c => c.Price),
                StoreName = p.Store == null ? "" : p.Store.Name,
                //WLSName = p.w
                JXSName = p.JXS == null ? "" : p.JXS.Name,
                MCName = p.MD == null ? "" : p.MD.Name,
                DGName = p.DG == null ? "" : p.DG.Name,
                FWSName = p.FWS == null ? "" : p.FWS.Name,
                CustomerName = p.CustomerName,
                CustomerTel = p.CustomerTel1 + "/" + p.CustomerTel2,
                Province = p.Province,
                City = p.City,
                County = p.County,
                Address = p.Address,
                CreateTime = p.CreateTime,
                Remarks = p.Remarks,
                CheckTime = p.JSXCheckTime,
                DeliverTime = p.WLDeliverTime
            }).ToList();
            return model.ToJQGridJSON(data.PageIndex, data.PageSize, data.TotalCount);
        }

        public ActionResult AddOrder()
        {
            var model = new OrderModel()
            {
                AvailableDG = _userService.GetUserByType(_workContext.CurrentUser, UserType.DG).ToSelectList(p => p.Name),
                AvailableFWS = _subordinateCompany.GetSubCompanyByType(_workContext.CurrentUser, SubordinateComapnyType.FWS).ToSelectList(p => p.Name),
                AvailableJXS = _subordinateCompany.GetSubCompanyByType(_workContext.CurrentUser, SubordinateComapnyType.JXS).ToSelectList(p => p.Name),
                AvailableMD = _subordinateCompany.GetSubCompanyByType(_workContext.CurrentUser, SubordinateComapnyType.MD).ToSelectList(p => p.Name),
                AvailableStore = _store.GetStore(_workContext.CurrentUser).ToSelectList(p => p.Name)

            };
            return View(model);
        }

        [HttpPost]
        public ActionResult AddOrder(OrderModel order)
        {
            var data = ToOrder(order);
            data.Status = (int)OrderStatus.AreaApprovalPending;
            _orderService.AddOrder(data);
            return Json(new
            {
                success = true,
                message = "添加成功"
            });
        }

        public ActionResult OrderInfo(int OrderId)
        {
            var data = _orderService.GetOrderById(OrderId);
            return View(ToModel(data));
        }
        #endregion

        #region 订单商品
        public string GetOrderItemList(int OrderId)
        {
            int pageSize = Convert.ToInt32(Request.QueryString["rows"]);
            int pageIndex = Convert.ToInt32(Request.QueryString["page"]) - 1;
            var data = _orderService.GetOrderProducts(OrderId, pageIndex, pageSize);
            List<object> model = data.Select(p => (object)new
            {
                Id = p.Id,
                Num = p.Product.Num,
                Name = p.Product.Name,
                Specification = p.Product.Specification,
                CatalogName = p.Product.Catalog.Name,
                Price = p.Price,
                Quantity = p.Quantity,
                Total = p.Quantity * p.Price,

OrderSystem/OrderSystem/Controllers/SubordinateCompanyController.cs
using Common;
using Common.Enums;
using Domain.Model.Comapnys;
using Domain.Model.Common;
using Domain.Model.Users;
using Domain.Services;
using Domain.Services.Comapnys;
using Domain.Services.Companys;
using Domain.Services.Users;
using Microsoft.Owin.Security;
using OrderSystem.Extensions;
using OrderSystem.Models.SubordinateCompany;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Mvc.Html;

namespace OrderSystem.Controllers
{
    public class SubordinateCompanyController : Controller
    {
        private IWorkContext _workContext;
        private ISubordinateCompanyService _subordinateCompanyService;
        private ICompanyService _iCompanyService;

        public SubordinateCompanyController(
            ISubordinateCompanyService subordinateCompany,
            IWorkContext workContext,ICompanyService iCompanyService)
        {
            _subordinateCompanyService = subordinateCompany;
            _workContext = workContext;
            _iCompanyService = iCompanyService;
        }
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult SubordinateCompanyList()
        {
            return View();
        }

        #region 经销商管理
        public ActionResult JXSCompanyList()
        {
            return View();
        }
        public ActionResult MCCompanyList()
        {
            return View();
        }
        public ActionResult WLSCompanyList()
        {
            return View();
        }
        public ActionResult FUSCompanyList()
        {
            return View();
        }

        public string GetSubordinateCompanyList()
        {
            int pageSize = Convert.ToInt32(Request.QueryString["rows"]);
            int pageIndex = Convert.ToInt32(Request.QueryString["page"]) - 1;
            SubordinateCompany parms = new SubordinateCompany();
            parms.Name = Request.QueryString["Name"];
            parms.Status = Convert.ToInt32(Request.QueryString["Status"]);
            parms.CompanyType = Convert.ToInt32(Request.QueryString["CompanyType"]);
            var data = _subordinateCompanyService.GetSubordinateCompanyList(parms, pageIndex, pageSize);

            List<object> model = data.Select(p => (object)new
            {
                Id = p.Id,
                Name = p.Name,
                Num = p.Num,
                Status = EnumExtensions.GetEnumDescription((Status)p.Status),
                Contacts = p.Contacts,
                ContactTel1 = p.ContactTel1,
                ContactTel2 = p.ContactTel2,
                Province = p.Province,
                City = p.City,
                County = p.County,
                Address = p.Address,
                ParentId = p.ParentId,
                CompanyType = EnumExtensions.GetEnumDescription((SubordinateComapnyType)p.CompanyType),
                CreateTime = p.CreateTime,
                CompanyId = p.CompanyId,
                Remarks = p.Remarks
        }).ToList();
            return model.ToJQGridJSON(data.PageIndex, data.PageSize, data.TotalCount);
        }

        public ActionResult AddSubordinateCompany()
        {
            var model = new SubordinateCompanyModel();

            model.SubordinateCompanyTypeList = EnumExtensions.GetSelectList<Domain.Model.Comapnys.SubordinateComapnyType>();
            model.StatusList = EnumExtensions.GetSelectList<Status>();
            Comapny parm = new Comapny();
            model.CompanyList =
                _iCompanyService.GetComapnyList(parm, 0,100).ToSelectList(p => p.Name);
            model.ParCompanyList =
                _subordinateCompanyService.GetSubCompanyByType(_workContext.CurrentUser, SubordinateComapnyType.ALL).ToSelectList(p => p.Name);
            model.CompanyType = Convert.ToInt32(Request.QueryString["CompanyType"]);
            return View(model);
        }

        [HttpPost]
        public ActionResult AddSubordinateCompany(SubordinateCompany user)
        {
            user.Comapny = _iCompanyService.GetById(user.CompanyId);
            _subordinateCompanyService.AddSubordinateCompany(user);
            return Json(new
            {
                success = true,
                message = "添加成功"
            });
        }

        [HttpPost]
        public ActionResult DelSubordinateCompany(int id)
        {
            _subordinateCompanyService.DelSubordinateCompany(id);
            return Json(new
            {
                success = true,
                message = "删除成功"
            });
        }

        public ActionResult UpdSubordinateCompany(int id)
        {
            var user = _subordinateCompanyService.GetSubCompanyById(id);
            SubordinateCompanyModel model = new SubordinateCompanyModel();
            model.Id = user.Id;
            model.Name = user.Name;
                model.Num = user.Num;

                model.Contacts = user.Contacts;

                model.ContactTel1 = user.ContactTel1;

                model.ContactTel2 = user.ContactTel2;

                model.Province = user.Province;

                model.City = user.City;

                model.County = user.County;

                model.Address = user.Address;

                model.Remarks = user.Remarks;

                model.Status = user.Status;

                model.ParentId = user.ParentId;

                model.CompanyType = user.CompanyType;

                model.CompanyId = user.CompanyId;

            List<SelectListItem> items = EnumExtensions.GetSelectList<Status>();
            foreach (SelectListItem item in items)
            {
                if (item.Value == Convert.ToString(model.Status))
                {
                    item.Selected = true;
                }
            }
            model.StatusList = items;


            items = EnumExtensions.GetSelectList<SubordinateComapnyType>();
            foreach (SelectListItem item in model.SubordinateCompanyTypeList)
            {
                if (item.Value == Convert.ToString(model.CompanyType))
                {
                    item.Selected = true;
                }
            }
            model.SubordinateCompanyTypeList = items;
                 
            items = _iCompanyService.GetComapnyList(new Comapny(), 0, 100).ToSelectList(p => p.Name);
            foreach (SelectListItem item in model.CompanyList)
            {
                if (item.Value == Convert.ToString(model.CompanyId))
                {
                    item.Selected = true;
                }
            }
            model.CompanyList = items;

            items = _subordinateCompanyService.GetSubCompanyByType(_workContext.CurrentUser, SubordinateComapnyType.ALL).ToSelectList(p => p.Name);
            foreach (SelectListItem item in model.SubordinateCompanyTypeList)
            {
                if (item.Value == Convert.ToString(model.ParentId))
                {
                    item.Selected = true;
                }
            }
            model.ParCompanyList = items;
            return View(model);
        }

        [HttpPost]
        public ActionResult UpdSubordinateCompany(SubordinateCompany user)
        {
            _subordinateCompanyService.UpdSubordinateCompany(user);
            return Json(new
            {
                success = true,
                message = "修改成功"
            });
        }

        [HttpPost]
        public ActionResult StopSubordinateCompany(int id)
        {
            _subordinateCompanyService.StopSubordinateCompany(id);
            return Json(new
            {
                success = true,
                message = "停用成功"
            });
        }
        #endregion
    }
}

OrderSystem/OrderSystem/Views/Home/Index.cshtml
@using Domain.Model.Users;
@{ 
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>广东万家乐物流配送系统1.0-运营管理</title>
    <link href="/Content/css/bootstrap.min14ed.css?v=3.3.6" rel="stylesheet">
    <link href="/Content/css/font-awesome.min93e3.css?v=4.4.0" rel="stylesheet">
    <link href="/Content/css/animate.min.css" rel="stylesheet">
    <link href="/Content/css/style.min862f.css?v=4.1.0" rel="stylesheet">

</head>
<body class="fixed-sidebar full-height-layout gray-bg" style="overflow:hidden">
    <div id="wrapper">
        <!--左侧导航开始-->
        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="nav-close">
                <i class="fa fa-times-circle"></i>
            </div>
            <div class="sidebar-collapse">
                <ul class="nav" id="side-menu">
    <li class="nav-header">
        <div class="dropdown profile-element">
            <span><img alt="image" src="~/Content/Images/LOGO.png" /></span>
        </div>
    </li>
    @{
        List<Menu> Menus = (List<Menu>)ViewData["AllMenu"];
        List<RoleMenus> roleMenus = (List<RoleMenus>)ViewData["RoleMenus"];
        foreach (RoleMenus item in roleMenus)
        {
            if (item.Menu.ParentId == 1)
            {
                <text>
                    <li>
    <a href="#">
        <i class="fa fa-home"></i>
        <span class="nav-label">
            @if (item.Menu.IfShow == 1)
            {@item.Menu.Name}
        </span>
        <span class="fa arrow"></span>
    </a>

                </text>
            List<Menu> subMenus = Menus.Where(a => { return a.ParentId == item.Menu.Id; }).ToList();
            if (subMenus.Count > 0)
            {
                    <text> <ul class="nav nav-second-level"></text>
                    foreach (Menu item2 in subMenus)
                    {
                        if (item2.IfShow == 1)
                        {
                            <text>
                                <li>
                                    <a class="@item2.IconClass" href="/@item2.ControllerName/@item2.ActionName" data-index="@item2.OrderNo">@item2.Name</a>
                                </li>
                            </text>
                        }

                }@:</ul>

            }

        }
    }
}</li>
                    @*<li> 
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">订单管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                @Html.ActionLink("添加订单", "OrderList", "Order", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("审核订单", "OrderCheckList", "Order", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("订单配送", "DeliveryList", "Order", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("订单查询", "OrderSearchList", "Order", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("订单明细查询", "OrderInfoList", "Order", null, new { @class = "J_menuItem" })
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">库存管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                @Html.ActionLink("进货入库", "QuestionClassList", "Question", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("入库单查询", "QuestionList", "Question", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("入库明细查询", "ImportQuestions", "Question", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("库存查询", "QuestionClassList", "Question", null, new { @class = "J_menuItem" })
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">报表管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                @Html.ActionLink("进货统计", "BookClassList", "Book", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("销售统计", "BooksList", "Book", null, new { @class = "J_menuItem" })
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">
                            <i class="fa fa-home"></i>
                            <span class="nav-label">系统管理</span>
                            <span class="fa arrow"></span>
                        </a>
                        <ul class="nav nav-second-level">
                            <li>
                                @Html.ActionLink("角色", "RoleList", "Account", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("菜单", "MenuList", "Account", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("用户", "UserAccountList", "Account", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("经销商", "JXSCompanyList", "SubordinateCompany", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("卖场", "MCCompanyList", "SubordinateCompany", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("物流商", "WLSCompanyList", "SubordinateCompany", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("服务商", "FUSCompanyList", "SubordinateCompany", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("商品品类", "CatalogList", "Product", null, new { @class = "J_menuItem" })
                            </li>
                            <li>
                                @Html.ActionLink("商品", "ProductList", "Product", null, new { @class = "J_menuItem" })
                            </li>
                        </ul>
                    </li>
                </ul>*@

</div>
        </nav>
        <!--左侧导航结束-->
        <!--右侧部分开始-->
        <div id="page-wrapper" class="gray-bg dashbard-1">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <div style="line-height:55px;"> <strong style="color:#78909c;font-size:18px">广东万家乐物流配送系统1.0</strong></div>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li class="hidden-xs">
                            <div class="topnav" style="line-height:55px;">

                                <div class="toprightnav">
                                    <span>当前用户：@Request.RequestContext.HttpContext.User.Identity.Name</span>
                                    <a id="btnUpdMyPwd" style="line-height:40px;padding:0 20px 0 25px;height:40px;margin-top:20px;border-right:solid 2px #ccc;">修改密码</a>
                                    @*@Html.ImageActionLink("/Content/images/off.png", "注销", "LogOut", "Account", new { }, new { @class = "tetoff" })*@
                                </div>
                            </div>
                        </li>
                        @*<li class="dropdown hidden-xs">
                                <a class="right-sidebar-toggle" aria-expanded="false">
                                    <i class="fa fa-tasks"></i> 主题
                                </a>
                            </li>*@
                    </ul>
                </nav>
            </div>
            <div class="row content-tabs">
                <button class="roll-nav roll-left J_tabLeft">
                    <i class="fa fa-backward"></i>
                </button>
                <nav class="page-tabs J_menuTabs">
                    <div class="page-tabs-content">
                        <a href="javascript:;" class="active J_menuTab" data-id="index_v1.html">首页</a>
                    </div>
                </nav>
                <button class="roll-nav roll-right J_tabRight">
                    <i class="fa fa-forward"></i>
                </button>
                <div class="btn-group roll-nav roll-right">
                    <button class="dropdown J_tabClose" data-toggle="dropdown">
                        关闭操作<span class="caret"></span>
                    </button>
                    <ul role="menu" class="dropdown-menu dropdown-menu-right">
                        <li class="J_tabShowActive">
                            <a>定位当前选项卡</a>
                        </li>
                        <li class="divider"></li>
                        <li class="J_tabCloseAll">
                            <a>关闭全部选项卡</a>
                        </li>
                        <li class="J_tabCloseOther">
                            <a>关闭其他选项卡</a>
                        </li>
                    </ul>
                </div>
                <a href="login.html" class="roll-nav roll-right J_tabExit"><i class="fa fa fa-sign-out"></i> 退出</a>
            </div>
            <div class="row J_mainContent" id="content-main">
                <iframe class="J_iframe" name="iframe0" width="100%" height="100%" src="/Home/HomePage" seamless></iframe>
            </div>
            <div class="footer">
                <div class="pull-right">

                </div>
            </div>
        </div>
        <!--右侧部分结束-->

    </div>
    <script src="~/Scripts/js/jquery.min.js?v=2.1.4"></script>
    <script src="~/Scripts/js/bootstrap.min.js?v=3.3.6"></script>
    <script src="~/Scripts/js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="~/Scripts/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/js/plugins/layer/layer.min.js"></script>
    <script src="~/Scripts/js/hplus.min.js?v=4.1.0"></script>
    <script type="text/javascript" src="~/Scripts/js/contabs.min.js"></script>
    <script src="~/Scripts/js/plugins/pace/pace.min.js"></script>
    <script src="~/Scripts/sanji/distpicker.data.js"></script>
    <script src="~/Scripts/sanji/distpicker.js"></script>
    <script src="~/Scripts/sanji/main.js"></script>
    <script src="~/Scripts/validateTools.js"></script>
    <script type="text/javascript">
            $(function () {
                // 绑定修改密码事件
                $('#btnUpdMyPwd').on('click', function (e) {
                    FormDialog("UpdPwddialog-form", "/Account/UpdMyPwd", "修改密码");
                })
            });

            function OnSuccessPost(e) {
                $("#UpdPwddialog-form").dialog("close");
                alert("操作成功！");
            }
    </script>
</body>
</html>